---
title: "Pheno Data from Jacob"
output: NULL
date: 3-11-2021
author: Jinliang Yang
---

```{r setup, include=TRUE}
#setwd("~/Documents/Github/pvpDiallel/")
knitr::opts_knit$set(root.dir=normalizePath('../'))
```

# Training set0

```{r}

getpheno_ULA <- function(trainfile="data/random_6k_folds_282Train_set.csv",
                     testfile="data/random_6k_folds_282Test_set.csv",
                     outfile="largedata/pheno/set"){
        
        tn <- read.csv(trainfile)
        # ln <- read.table("largedata/genotype/lines.txt", header=TRUE)

        test <- read.csv(testfile)
        pheno <- read.csv("data/3a1o_m282.UpperLeafAngle.BLUE.csv")
        pheno <- subset(pheno, !is.na(UpperLeafAngle)) 
        for(i in 0:10){
          tn0 <- subset(tn, Fold == i)
          # test <- merge(tn0, ln, by.x="Taxa", by.y="FID")
         
          # training data
          out1 <- merge(tn0, pheno[, c("Line", "UpperLeafAngle")], by.x="Taxa", by.y="Line")
          out1 <- out1[, c("Taxa", "UpperLeafAngle", "Set")]
          names(out1) <- c("FID", "ULA", "Fix")
          out1$Fix <- 1

          write.table(out1, paste0(outfile, i, "_train.txt"), sep="\t", row.names=FALSE, quote=FALSE)
          
          test0 <- subset(test, Fold == i)
          # test data
          out2 <- merge(test0, pheno[, c("Line", "UpperLeafAngle")], by.x="Taxa", by.y="Line")
          out2 <- out2[, c("Taxa", "UpperLeafAngle", "Set")]
          names(out2) <- c("FID", "ULA", "Fix")
          out2$Fix <- 1
          write.table(out2, paste0(outfile, i, "_test.txt"), sep="\t", row.names=FALSE, quote=FALSE)
        }
}


```

-----------
3/11/2021

### Random:

```{r}
getpheno_ULA(trainfile="data/random_11k_folds_282Train_set_12Dec2020.csv",
         testfile="data/random_11k_folds_282Test_set_12Dec2020.csv",
         outfile="largedata/ULA/random/set")

```

## Kmean
```{r}
getpheno_ULA(trainfile="data/kmeans_11k_folds_282Train_set_12Dec2020.csv",
         testfile="data/kmeans_11k_folds_282Test_set_12Dec2020.csv",
         outfile="largedata/ULA/kmeans/set")

```
