---
title: "Data from Jacob"
output: NULL
author: Jinliang Yang
---

Hello all,
 
Here is the training and testing set data based on kmeans clustering of the cultivars using the 1 Million random kmers data.
 
I have attached a file for each data set (282 training, 282 testing, and NAMtesting). Each file has a column for the fold number (0-5), a column for the set it is in (this is redundant with the file name) and a column for the Taxa (cultivars in that fold and set). The 282 have had all NAM founders removed so that all of our training will be done without the NAM included.  For each fold there is a 282Training Set, 282Testing Set, and a NAMTesting Set.  In some cases there are no NAM founders within a cluster so that set is zero for some folds.  Here are the numbers of cultivars in each fold’s Train, test, and NAM test set:
 
Fold       Train      Test        Test_NAM
0             200         45           4
1             232         13           0
2             151        94           0
3             226        19           3
4             225        20           1
5             191        54           18
 
As you can see, some folds have larger testing sets than others.  I would like to have had more similar test set sizes, but this is the way the clustering came out.  Jinliang, do you have any concerns about this or do you think it is ok?  One strategy we could use after the fact is to randomly drop test set cultivars so that all test sets are the same size…
 
Cheng, for your GWAS analysis all you need to worry about is the 282Train file.  You need to run 6 different GWAS and determine the significant k-mers for each.  You should be able to just take the cultivars for fold 0 and run a GWAS on them, then the ones for fold 1 and run a separate GWAS on them, etc.  After you run the analysis and find the significant kmers, then I will need a file/list containing those kmers and their abundances across all cultivars (a different file/list for each fold).
 
Let me know if that makes sense or if we should change anything in this strategy before moving forward.
 
Thanks,
 
Jacob


----------

Hi Jinliang,
 
Here are the new k-fold groupings based on the 282 set only.  When I ran the analysis this time k=11 seemed to be the best separation of the groups. For that reason I also made a new random splitting (no population structure) set with 11 folds.  Please find both attached.
 
To summarize, we need you to re-run the flowering time predictions using the new sets (kmeans_11k and random_11k), and run the UAL data for both of the same sets.
 
Let me know if you have any questions.
 
Thanks,
 
Jacob